### ISSUE TITLE
Erro ao tentar receber cmd no whatsapp

### ISSUE THREAD

**Issue by AlbertEinsteinGlitchPoint** [HelioSilva/template-node-typescript#1]
Bom dia, segui o tutorial e instalei tudo, consegui arrancar o app e o venom, conecto normal via qr code e mostra conectado..

quando envio a palavra Hi  ele reconhece no APP mas trava..

dando o seguinte erro.

info:     [BOT] Page successfully accessed
✓ [instance: BOT]: Connected
Error: Evaluation failed: ReferenceError: Cannot access 'o' before initialization
    at Object.window.WAPI.window.WAPI.sendExist (/opt/template-node-typescript/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:33189)
    at async Object.window.WAPI.window.WAPI.sendMessage (/opt/template-node-typescript/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:47206)
    at ExecutionContext._evaluateInternal (/opt/template-node-typescript/node_modules/puppeteer/src/common/ExecutionContext.ts:273:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at ExecutionContext.evaluate (/opt/template-node-typescript/node_modules/puppeteer/src/common/ExecutionContext.ts:140:12)
[ERROR] 12:14:08 Error: Evaluation failed: ReferenceError: Cannot access 'o' before initialization
    at Object.window.WAPI.window.WAPI.sendExist (/opt/template-node-typescript/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:33189)
    at async Object.window.WAPI.window.WAPI.sendMessage (/opt/template-node-typescript/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:47206)

a configuracão está exatamente igual ao video tutorial no youtube.

**Comment by HelioSilva** [comment]
Bom dia,

-  Primeiro verifica se está na versão mais recente do vennom-bot.
-  Se mesmo assim persistir o problema, procura outro repositório para bot, todos os outros são semelhantes.

Exemplos de repositórios:

https://github.com/pedroslopez/whatsapp-web.js
https://github.com/wppconnect-team/wppconnect
